version: "3.10"

services:

  api:
    build: .
    container_name: hr_ai_api
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:root@postgres:5432/hr_ai
      REDIS_URL: redis://redis:6379

  worker:
    build: .
    container_name: hr_ai_worker
    command: python backend/worker.py
    depends_on:
      - redis
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:root@postgres:5432/hr_ai
      REDIS_URL: redis://redis:6379

  redis:
    image: redis:7
    container_name: hr_ai_redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: hr_ai_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hr_ai
    ports:
      - "5432:5432"